### ISSUE TITLE
Does not compile with GCC 4.7

### ISSUE THREAD

**Issue by lusentis** [shovon/sync-prompt#4]
Tested on Ubuntu (CrunchBang 11 waldorf)

```
node -v && npm -v
v0.10.20
1.3.11
```

```
~/node-v0.10.20-linux-x64/lib/node_modules  ᐅ npm install sync-prompt
npm http GET https://registry.npmjs.org/sync-prompt
npm http 304 https://registry.npmjs.org/sync-prompt

> sync-prompt@0.2.1 install /home/simone/node-v0.10.20-linux-x64/lib/node_modules/sync-prompt
> node-gyp rebuild

make: Entering directory `/home/simone/node-v0.10.20-linux-x64/lib/node_modules/sync-prompt/build'
  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc: In function ‘void setStdinEcho(bool)’:
../src/sync_prompt.cc:30:13: error: ‘STDIN_FILENO’ was not declared in this scope
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
make: Leaving directory `/home/simone/node-v0.10.20-linux-x64/lib/node_modules/sync-prompt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/simone/node-v0.10.20-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/home/simone/node-v0.10.20-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/simone/node-v0.10.20-linux-x64/lib/node_modules/sync-prompt
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

[This](https://wl.widelands.org/forum/topic/1043/?page=1#post-7931) should solve the issue.
